### ISSUE TITLE
Can current program solve DOUBLE data type for coordinates?

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/accessAndMySQLTransfer#1]
In the codes below in access2mysql.ipynb, the common Access data types were converted to MySQL data types:

        type_name = type_name if type_name != 'VARCHAR' else 'VARCHAR(255)'
        type_name = type_name if type_name != 'LONGCHAR' else 'LONGTEXT'
        type_name = type_name if type_name != 'BYTE' else 'SMALLINT'
        type_name = type_name if type_name != 'COUNTER' else 'INTEGER'

However, DOUBLE was not there. Will the sentences above can solve address coordinates data types which were DOUBLE decimal?

Thanks

**Comment by funqc** [comment]
这里处理的是access和mysql不一样的类型，我好像记得access和mysql的double类型是一样的，所以没有加转换处理
