### ISSUE TITLE
您好，我现在遇到一个问题，如何在创建表的时候添加字段注释呢

### ISSUE THREAD

**Issue by fangpeng0011** [cbdb-project/accessAndMySQLTransfer#3]
我对您的程序进行了修改，能够获取到字段的注视，但是在创建Access的时候提示我语法错误，请问有没有什么办法能够将注释添加上呢，非常感谢

**Comment by sudoghut** [comment]
谢谢您对本项目感兴趣！我们在工作中比较少和字段注释打交道，可能没办法向你提供太多帮助。如果您找到解决方案，欢迎在本 issue 下向开源社区的大家分享。
